---
info:
  title: Cpe Utils
  description: A simple python library to assist in working with cpes
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/cpe_utils
  x-cortex-tag: cpe-utils
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
  x-cortex-groups:
  - exposure:internal-ship
openapi: 3.0.1
servers:
- url: "/"
